apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: grafana-monitoring
  name: grafana-monitoring
  namespace: kube-system
spec:
  replicas: 1
  selector:
    name: grafana-monitoring
  template:
    metadata:
      labels:
        name: grafana-monitoring
    spec:
      hostNetwork: true
      containers:
      - name: grafana-monitoring
        image: kubernetes/heapster_grafana:v2.1.0
        env:
          - name: INFLUXDB_SERVICE_URL
            value: http://master:8086
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
          #- name: GF_SERVER_ROOT_URL
          #  value: /api/v1/proxy/namespaces/default/services/grafana-monitoring/
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
      volumes:
      - name: grafana-storage
        emptyDir: {}
