apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-monitoring
  name: grafana-monitoring
  namespace: kube-system
spec:
  ports:
  - name: grafana
    port: 3000
  selector:
    name: grafana-monitoring