apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: heapster
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    name: heapster
  template:
    metadata:
      labels:
        name: heapster
    spec:
      hostNetwork: true
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster:v1.1.0
        command:
        - /heapster
        - --source=kubernetes:http://master:8080?inClusterConfig=false
        - --sink=influxdb:http://master:8086
        - --v=4
