apiVersion: v1
kind: ReplicationController
metadata:
  name: stolon-proxy-rc
spec:
  replicas: 1
  selector:
    name: stolon-proxy
  template:
    metadata:
      labels:
        name: stolon-proxy
        stolon-cluster: "kube-stolon"
        stolon-proxy: "true"
    spec:
      containers:
      - name: stolon-proxy
        image: sorintlab/stolon:v0.2.0
        env:
          - name: PROXY
            value: "true"
          - name: STPROXY_CLUSTER_NAME
            value: "kube-stolon"
          - name: STPROXY_ETCD_ENDPOINTS
            value: "http://172.16.32.10:2379"
        ports:
          - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          timeoutSeconds: 5
