apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp-controller
spec:
  replicas: 1
  selector:
    name: webapp
  template:
    spec:
      containers:
        - name: webapp
          image: localhost:5000/webapp
          ports:
            - containerPort: 80
    metadata:
      labels:
        name: webapp
        uses: db