# -*- mode: ruby -*-
# vi: set ft=ruby :

domain = 'example.com'

nodes = [
    {:hostname => 'node1',  :ip => '172.16.32.11'},
    {:hostname => 'node2',  :ip => '172.16.32.12'},
    {:hostname => 'node3',  :ip => '172.16.32.13'},
]

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "shell", name: "Init machine", inline: <<-SHELL
      set -ex
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
      apt-get update -qy
      apt-get install -y docker.io kubelet kubeadm kubectl kubernetes-cni
      echo -e "172.16.32.11 node1\\n172.16.32.12 node2\\n172.16.32.13 node3" | sudo tee -a /etc/hosts
  SHELL

  nodes.each do |node_config|
      config.vm.define node_config[:hostname] do |node|
          node.vm.hostname = node_config[:hostname] + '.' + domain
          node.vm.network "private_network", ip: node_config[:ip]
          node.vm.provider "virtualbox" do |v|
              v.memory = 1024
              v.cpus = 1
              v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
          end
      end
  end
end
