apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - /hyperkube
    - scheduler
    - --master=https://127.0.0.1
    - --kubeconfig=/etc/kubernetes/shared/kubeconfig
    - --alsologtostderr
    - --enable-load-reader
    - --v=3
    - --leader-elect
    image: gcr.io/google_containers/hyperkube:v1.4.5
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: kubernetes-confdir
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: kubernetes-confdir
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host