---
  kind: Pod
  apiVersion: v1
  metadata:
    name: kube-controller-manager
    namespace: kube-system
  spec:
    hostNetwork: true
    containers:
      - name: kube-controller-manager
        image: gcr.io/google_containers/hyperkube:v1.3.4
        command:
          - /hyperkube
          - controller-manager
          - --master=https://master.example.com
          - --kubeconfig=/etc/kubernetes/shared/kubeconfig
          - --alsologtostderr
          - --enable-load-reader
          - --v=3
          - --leader-elect
          - --root-ca-file=/etc/kubernetes/shared/ssl/ca.pem
          - --service-account-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
          - --service-cluster-ip-range=10.10.0.0/16
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 10252
          initialDelaySeconds: 15
          timeoutSeconds: 15
        volumeMounts:
        - mountPath: /etc/kubernetes
          name: kubernetes-confdir
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
    volumes:
    - hostPath:
        path: /etc/kubernetes
      name: kubernetes-confdir
    - hostPath:
        path: /usr/share/ca-certificates
      name: ssl-certs-host