---
  kind: Pod
  apiVersion: v1
  metadata:
    name: kube-scheduler
    namespace: kube-system
  spec:
    hostNetwork: true
    containers:
      - name: kube-scheduler
        image: gcr.io/google_containers/hyperkube:v1.3.4
        command:
          - /hyperkube
          - scheduler
          - --master=https://master.example.com
          - --kubeconfig=/etc/kubernetes/shared/kubeconfig
          - --alsologtostderr
          - --enable-load-reader
          - --v=3
          - --leader-elect
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 10251
          initialDelaySeconds: 15
          timeoutSeconds: 15
        volumeMounts:
        - mountPath: /etc/kubernetes
          name: kubernetes-confdir
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
    volumes:
    - hostPath:
        path: /etc/kubernetes
      name: kubernetes-confdir
    - hostPath:
        path: /usr/share/ca-certificates
      name: ssl-certs-host