---
  kind: Pod
  apiVersion: v1
  metadata:
    name: kube-apiserver
    namespace: kube-system
  spec:
    hostNetwork: true
    containers:
      -
        name: "kube-apiserver"
        image: "gcr.io/google_containers/hyperkube:v1.2.4"
        command:
          - /hyperkube
          - apiserver
          - --insecure-bind-address=0.0.0.0
          - --etcd_servers=http://127.0.0.1:2379
          - --allow-privileged=true
          - --service-cluster-ip-range=10.254.0.0/16
        ports:
          -
            name: "https"
            hostPort: 443
            containerPort: 443
          -
            name: "local"
            hostPort: 8080
            containerPort: 8080
        volumeMounts:
          -
            name: "etcssl"
            mountPath: "/etc/ssl"
            readOnly: true
          -
            name: "config"
            mountPath: "/etc/kubernetes"
            readOnly: true
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 15
    volumes:
      -
        name: "etcssl"
        hostPath:
          path: "/etc/ssl"
      -
        name: "config"
        hostPath:
          path: "/etc/kubernetes"
