---
  kind: Pod
  apiVersion: v1
  metadata:
    name: kube-controller-manager
    namespace: kube-system
  spec:
    hostNetwork: true
    containers:
      -
        name: "kube-controller-manager"
        image: gcr.io/google_containers/hyperkube:v1.2.4
        command:
          - /hyperkube
          - controller-manager
          - --master=http://master:8080
          - --v=3
        volumeMounts:
          -
            name: "etcssl"
            mountPath: "/etc/ssl"
            readOnly: true
          -
            name: "config"
            mountPath: "/etc/kubernetes"
            readOnly: true
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 10252
          initialDelaySeconds: 15
          timeoutSeconds: 15
    volumes:
      -
        name: "etcssl"
        hostPath:
          path: "/etc/ssl"
      -
        name: "config"
        hostPath:
          path: "/etc/kubernetes"
