apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    tier: node
    component: kube-proxy
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube:v1.4.5
    resources:
      requests:
        cpu: 100m
    command:
    - /hyperkube
    - proxy
    - --master=https://master.example.com
    - --kubeconfig=/etc/kubernetes/shared/kubeconfig
    - --alsologtostderr
    - --enable-load-reader
    - --v=2
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: kubernetes-confdir
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: kubernetes-confdir
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host