version: '2'
services:
  webapp:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "80:80"
    links:
      - postgres

  postgres:
    restart: unless-stopped
    image: postgres:9.5
    environment:
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: webapp
